spring.application.name=urlshortener

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis disabled for now
spring.cache.type=none

app.base-url=${BASE_URL}

server.port=${PORT:8080}